In [2]:
import numpy as np

In [5]:
# Output an array by repeating a smaller array of 2 dimensions, 10 times
x = np.array([[1, 2, 3],
             [4, 5, 6]])
np.tile(x, 7)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [6]:
# Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)
np.random.seed(123) # setting the seed
np.random.randint(0, 10, size = (5, 5))

array([[2, 2, 6, 1, 3],
       [9, 6, 1, 0, 1],
       [9, 0, 0, 9, 3],
       [4, 0, 0, 4, 1],
       [7, 3, 2, 4, 7]])

In [7]:
# Output a 3-by-3 array of random numbers following normal distribution
np.random.seed(123) # setting the seed
np.random.normal(size = (3,3))

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654],
       [-2.42667924, -0.42891263,  1.26593626]])

In [8]:
# Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])
np.matmul(a, b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [9]:
# Output the transpose of a matrix (as numpy array)
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
# Write a NumPy program to test whether none of the elements of a given array is zero.a
a = np.array([1, 2, 3])
b = np.array([[1,2,3],
              [4,5,0],
              [7,8,9]])
np.all(a)


True

In [15]:

np.all(b)

False

In [17]:
# Write a NumPy program to test whether any of the elements of a given array is non-zero
np.any(a)

True

In [19]:
np.any(b)

True

In [20]:
# Write a NumPy program to test a given array element-wise 
# for finiteness (not infinity or not a Number).
a = np.array([1, 0, np.nan, np.inf])
np.isfinite(a)

array([ True,  True, False, False])

In [21]:
# Write a NumPy program to test element-wise for NaN of a given array.
b = np.array([1, 0, np.nan, np.inf])
np.isnan(b)

array([False, False,  True, False])

In [22]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


In [25]:
x = [12.23, 13.32, 100, 36.32]
b = np.array(x)
print(b)

[ 12.23  13.32 100.    36.32]
