In [2]:
import pandas as pd
import numpy as np
pd.__version__

'1.2.4'

In [2]:
pd?

In [4]:
data = pd.Series([0.25, 0.5,0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
data[1]

0.5

In [8]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [9]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [10]:
data['b']

0.5

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [12]:
data[5]

0.5

In [13]:
population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}

In [14]:
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

In [17]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995}

In [18]:
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [19]:
states = pd.DataFrame({'population': population,
'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [20]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [21]:
states.columns

Index(['population', 'area'], dtype='object')

In [24]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [25]:
states['area']['Texas']

695662

In [26]:
# Constructing DataFrame objects
# From a single Series object.
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [27]:
# From a list of dicts.
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [28]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [29]:
# From a dictionary of Series objects.
pd.DataFrame({'population': population, 'area': area})

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [31]:
# From a two-dimensional NumPy array.
pd.DataFrame(np.random.rand(3, 2),columns=['foo', 'bar'],index=['a', 'b', 'c'])

foo       bar
a  0.087978  0.687854
b  0.290795  0.048724
c  0.738361  0.470817

In [32]:
# From a NumPy structured array
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [34]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [35]:
# The Pandas Index Object
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [36]:
# Index as immutable array
ind[1]

3

In [37]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [38]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [39]:
# Index as ordered set
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [41]:
# intersection
# indA & indB ======>deprecated
indA.intersection(indB)


Int64Index([3, 5, 7], dtype='int64')

In [43]:
# union
# indA | indB =======> deprecated
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [45]:
# symmetric difference
# indA ^ indB=============> deprecated
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

In [46]:
# Data Selection in Series
data = pd.Series([0.25, 0.5, 0.75, 1.0],
index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [47]:
'a' in data

True

In [48]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [49]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [50]:
# Series can be modify
data['e'] = 1.25

In [51]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [52]:
# Series as one-dimensional array
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [53]:
# slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [54]:
# masking
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [55]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [56]:
# Indexers: loc, iloc, and ix
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [57]:
# explicit index when indexing
data[1]

'a'

In [58]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [59]:
# loc attribute allows indexing and slicing that always references the explicit index:
data.loc[1]

'a'

In [60]:
data.loc[1:3]

1    a
3    b
dtype: object

In [61]:
# The iloc attribute allows indexing and slicing that always references the implicit
# Python-style index
data.iloc[1]

'b'

In [62]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [3]:
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [4]:
# The individual Series that make up the columns of the DataFrame can be accessed
# via dictionary-style
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [5]:
# we can use attribute-style access with column names that are strings
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [6]:
data.area is data['area']

True

In [7]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [8]:
# We can examine the raw underlying data array using the values attribute
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [9]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [11]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [12]:
data.loc[:'Illinois', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [14]:
# Display row where density is greater than 100 and column of pop and density
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [15]:
# update row 0 column 2 with a value of 90
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [16]:
rng = np.random.RandomState(42)

In [17]:
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [19]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)), columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [20]:
# Preserve the indices when applying to any numpy func
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [21]:
np.sin(df * np.pi / 4)

A         B         C         D
0  7.071068e-01 -0.707107 -0.707107  0.707107
1  1.224647e-16  0.000000  0.707107 -0.707107
2 -2.449294e-16  0.000000  0.707107  1.000000

In [22]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127}, name='population')

In [23]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [25]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [26]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [27]:
# If using NaN values is not the desired behavior, we can modify the fill value using
# appropriate object methods in place of the operators.
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [28]:
# Index alignment in DataFrame

A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
columns=list('AB'))
A

A   B
0  11  19
1   2   4

In [29]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
columns=list('BAC'))
B

B  A  C
0  2  6  4
1  8  6  1
2  3  8  1

In [30]:
A + B

A     B   C
0  17.0  21.0 NaN
1   8.0  12.0 NaN
2   NaN   NaN NaN

In [31]:
# we’ll fill with the mean of all values in A (which we compute
# by first stacking the rows of A )
fill = A.stack().mean()

In [32]:
A.add(B, fill_value=fill)

A     B     C
0  17.0  21.0  13.0
1   8.0  12.0  10.0
2  17.0  12.0  10.0

In [33]:
# Ufuncs: Operations Between DataFrame and Series
# Operations between a DataFrame and
# a Series are similar to operations between a two-dimensional and one-dimensional
# NumPy array.
A = rng.randint(10, size=(3, 4))
A

array([[9, 8, 9, 4],
       [1, 3, 6, 7],
       [2, 0, 3, 1]])

In [34]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-8, -5, -3,  3],
       [-7, -8, -6, -3]])

In [35]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -8 -5 -3  3
2 -7 -8 -6 -3

In [36]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  1  0  1 -4
1 -2  0  3  4
2  2  0  3  1

In [ ]:
# Handling Missing Data